# Generated by Django 4.2.11 on 2026-03-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='tour_images/'),
        ),
    ]
