# Generated by Django 6.0.3 on 2026-03-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tourpackage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='provider_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
